type Task {
  _id: ID!
  title: String
  description: String!
  user: User!
}

input TaskInput {
  title: String
  description: String
  user: ID
}

type Query {
  tasks: [Task!]!
  task(id: ID!): Task!
}

type Mutation {
  createTask(data: TaskInput!): Task!
  updateTask(id: ID!, data: TaskInput!): Task!
  deleteTask(id: ID!): Boolean!
}